### PR TITLE
Fixed actorparsing - rotation TypeError

### PR DESCRIPTION
**Pull request by twobackfromtheend**

### CODE REVIEW

**Comment by Sciguymjm** [comment]
Does this actually fix it or is just going to ignore the error?

**Comment by twobackfromtheend** [comment]
I think the error is not ignoring it. It's just None and when it's None we have no business scaling it. Looked at the ball and player dataframes for his replay and they looked fine.

**Comment by enzanki-ars** [comment]
I tested this PR on the same replay, and it parses.  Must be just a weird replay, as this project reports a couple other strange things about it, for example a goal not being a shot and no camera settings for myself.

**Comment by twobackfromtheend** [comment]
Goal not being a shot is a common thing - our shot detection is good but not perfect, also own goals would lead to the "no shot for goal" thing.

The no camera settings is strange as the other players do have camera settings - needs to be debugged by looking at the json

**Pull request merged**
